// games.js
export const consoles = {
    "Populares no GBA": { 
        key: "GBA", 
        games: [
            { title: "Sonic Advance", image: "https://static.wikia.nocookie.net/sonic-the-hedgehog/images/c/c8/Sonic_Advance_-_North-american_cover.jpg/revision/latest?cb=20140422212552&path-prefix=pt", url: "https://www.retrogames.cc/embed/28783-sonic-advance-j-independent.html" },
            { title: "Sonic Advance 2", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq8Zuafu5APhI-2R8mxcn4vgFx1O1UMBf2er4udPmo6Nrl_BWq2hGY4Fie&s=10", url: "https://www.retrogames.cc/embed/28169-sonic-advance-2-j-eurasia.html" },
            { title: "Sonic Advance 3", image: "https://static.wikia.nocookie.net/sonic-the-hedgehog/images/4/49/Capa4.jpg/revision/latest?cb=20140422214257&path-prefix=pt", url: "https://www.retrogames.cc/embed/19452-sonic-advance-3-e-trashman.html" },
            { title: "Sonic Battle", image: "https://upload.wikimedia.org/wikipedia/en/8/88/Sonic_Battle_Coverart.png", url: "https://www.retrogames.cc/embed/26763-sonic-battle-j-eurasia.html" },
            { title: "Sonic Pinball Party", image: "https://upload.wikimedia.org/wikipedia/en/f/f5/Sonicpp.png", url: "https://www.retrogames.cc/embed/19365-sonic-pinball-party-u-venom.html"},
            { title: "Sonic The Hedgehog - Genesis", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZP5rB7AM24N2mNBR47exseLGJNQc_2vKtqRUvxNsD1F1ICdXQCQWJAEaW&s=10", url: "https://www.retrogames.cc/embed/27910-sonic-the-hedgehog-genesis-u-trashman.html"},
            { title: "Mega Man Zero", image: "https://images.uncyc.org/pt/8/82/Megaman_zero.jpg", url: "https://www.retrogames.cc/embed/19499-megaman-zero-u-venom.html" },
            { title: "Mega Man Zero 2", image: "https://i.ebayimg.com/images/g/oeUAAOSwQ4FkmgSb/s-l1200.jpg", url: "https://www.retrogames.cc/embed/26254-megaman-zero-2-e-patience.html" },
            { title: "Mega Man Zero 3", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrfYb9f1x_Y4FLaSZRJ_rWW7yIIlaJ4O0m5WGPVRr_-gKAEW6i1vyLi5g&s=10", url: "https://www.retrogames.cc/embed/19493-megaman-zero-3-e-rising-sun.html" },
            { title: "Mega Man Zero 4", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdnLt90ABm3hyIvFSjpoJzEcHTElpDjTEFrl7ameh4vUltUtBJ0JBEKdpr&s=10", url: "https://www.retrogames.cc/embed/28027-megaman-zero-4-e-supplex.html" },
            { title: "MegaMan Battle Network", image: "https://upload.wikimedia.org/wikipedia/en/c/cb/Megamanbattlenetwork_boxshot.jpg", url: "https://www.retrogames.cc/embed/27902-megaman-battle-network-e-rocket.html"},
            { title: "MegaMan Battle Network 2", image: "https://upload.wikimedia.org/wikipedia/en/c/cb/Mega_Man_Battle_Network_2_Coverart.png", url: "https://www.retrogames.cc/embed/26281-megaman-battle-network-2-u-mode7.html"},
            { title: "MegaMan Battle Network 3", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_zOy7IgigNEiQFc_UdhZ1sewqQ4ePtsEA6Agozl04DsmtrD1FaqH-ER0&s=10", url: "https://www.retrogames.cc/embed/27716-megaman-battle-network-3-white-version-u-mode7.html"},
            { title: "MegaMan Battle Network 4", image: "https://bdjogos.com.br/capas/14834-mega-man-battle-network-4-blue-moon-game-boy-advance-capa-1.jpg", url: "https://www.retrogames.cc/embed/26877-megaman-battle-network-4-red-sun-u-independent.html"},
            { title: "Megaman Battle Network 5", image: "https://bdjogos.com.br/capas/14837-mega-man-battle-network-5-team-protoman-game-boy-advance-capa-1.jpg", url: "https://www.retrogames.cc/embed/26570-megaman-battle-network-5-team-protoman-u-trashman.html"},
            { title: "MegaMan Battle Network 6", image: "https://www.lukiegames.com/assets/images/GBA/gba_mega_man_battle_network_6_falzar_p_0clcb6.jpg", url: "https://www.retrogames.cc/embed/27799-megaman-battle-network-6-cybeast-falzar-u-independent.html"},
            { title: "Megaman Battle Chip Challenge", image: "https://m.media-amazon.com/images/I/61BX40RD7ML.jpg", url: "https://www.retrogames.cc/embed/29094-megaman-battle-chip-challenge-e-rising-sun.html"},
            { title: "Dragonball Advanced Adventure", image: "https://cdn.emulatorgamer.com/covers/gba/dragon-ball-advanced-adventure.webp", url: "https://www.retrogames.cc/embed/26252-dragonball-advanced-adventure-e-rising-sun.html"},
            { title: "Dragon Ball Z: Supersonic Warriors", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVZGVrMdwznydtiP1_CW5Dytg7gRLDwbAc2KQOFT7GS3BU230bReww4hRy&s=10", url: "https://www.retrogames.cc/embed/19537-dragonball-z-supersonic-warriors-e-rising-sun.html"},
            { title: "Dragon Ball Z: The Legacy of Goku", image: "https://static.wikia.nocookie.net/dragonball/images/5/55/Dragon_Ball_Z_Legacy_of_Goku_Packshot.jpg/revision/latest?cb=20171105221212&path-prefix=pt-br", url: "https://www.retrogames.cc/embed/26814-dragon-ball-z-the-legacy-of-goku-e-polla.html"},
            { title: "Dragon Ball Z: The Legacy of Goku II", image: "https://bdjogos.com.br/capas/14792-dragon-ball-z-the-legacy-of-goku-ii-game-boy-advance-capa-1.jpg", url: "https://www.retrogames.cc/embed/27814-dragon-ball-z-the-legacy-of-goku-ii-e-eurasia.html"},
            { title: "Dragon Ball Z: Buu's Fury", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO70PNRRiC52liAq08t-wNKT9jz9L8RjEVZg4tgGMvNy8HEOABazl4iFw&s=10", url: "https://www.retrogames.cc/embed/28935-dragon-ball-z-buu-s-fury-u-psychosis.html"},
            { title: "Dragon Ball GT: Transformation", image: "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Transformation_cover.JPG/250px-Transformation_cover.JPG", url: "https://www.retrogames.cc/embed/27773-dragon-ball-gt-transformation-u-trashman.html"},
            { title: "Pokemon Ephemerald", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0D4yyEY2olIpxgN0ML-OK9fLd8GGJw0EfP0uxnNQagyOHUftJkg3uoTI&s=10", url: "https://www.retrogames.cc/embed/42901-pokemon-ephemerald-v1-0.html"},
            { title: "Pokemon Fire Red", image: "https://bdjogos.com.br/capas/14795-pokemon-firered-version-game-boy-advance-capa-1.jpg", url: "https://www.retrogames.cc/embed/42901-pokemon-ephemerald-v1-0.html"},
            { title: "Kirby: The Amazing Mirror", image: "https://m.media-amazon.com/images/I/71CUMPFnXdL.jpg", url: "https://www.retrogames.cc/embed/19385-kirby-and-the-amazing-mirror-e-rising-sun.html"},
            { title: "Kirby: Nightmare in Dreamland", image: "https://static.wikia.nocookie.net/kirby/images/f/f8/KNiD_Boxart.jpg/revision/latest?cb=20080719011713&path-prefix=en", url: "https://www.retrogames.cc/embed/26683-kirby-nightmare-in-dreamland-u-mode7.html"},
        ]
    },
    "Ação no Nintendo DS": { 
        key: "NDS", 
        games: [
            { title: "Ben 10: Protector of Earth", image: "https://jffvideogames.com/cdn/shop/products/ben_10_protector_of_earth.jpg?v=1615579773", url: "https://www.retrogames.cc/embed/36951-ben-10-protector-of-earth-europe-en-fr-de-es-it.html" },
            { title: "Ben 10: Alien Force", image: "https://m.media-amazon.com/images/I/71C3ZF7r-KL.jpg", url: "https://www.retrogames.cc/embed/38112-ben-10-alien-force-usa-en-fr-de-es-it-rev-1.html" },
            { title: "Ben 10: Alien Force - Vilgax Attacks", image: "https://m.media-amazon.com/images/I/71ByV7Dc+eL._AC_UF1000,1000_QL80_.jpg", url: "https://www.retrogames.cc/embed/39567-ben-10-alien-force-vilgax-attacks-europe-en-fr-de-es-it.html" },
            { title: "Ben 10 Ultimate Alien: Cosmic Destruction", image: "https://m.media-amazon.com/images/I/71WDtkDAenL.jpg", url: "https://www.retrogames.cc/embed/42018-ben-10-ultimate-alien-cosmic-destruction-usa-en-fr-de-es-it.html"},
            { title: "Ben 10: Galactic Racing", image: "https://i.ebayimg.com/images/g/960AAAzykWJSr1XD/s-l640.jpg", url: "https://www.retrogames.cc/embed/46431-ben-10-galactic-racing-usa-en-fr-de-es-it.html" },
            { title: "Ben 10: Omniverse", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA_PkWhCs5fHicvV0XyyUbLtxecGDSbt82Ff6azoTzGqN69paEUgGPpXQ&s=10", url: "https://www.retrogames.cc/embed/42019-ben-10-omniverse-usa-en-fr-es.html" },
            { title: "Dragon Ball Z: Supersonic Warriors 2", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQObpZ3VNBLgD1wBIBfsAD5wW-NJgNvPm6w3yeyzeBSFCdxbjrgHDzOUB9m&s=10", url: "https://www.retrogames.cc/embed/35336-dragon-ball-z-supersonic-warriors-2-usa.html"},
            { title: "Dragon Ball: Origins", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVlVMmh9xJNOhGYHD7sdv4laxeTlFyWw-3CYwyCfSCWg&s=10", url: "https://www.retrogames.cc/embed/38014-dragon-ball-origins-usa.html"},
            { title: "Dragon Ball: Origins 2", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8L82QBXV7aPD9DSgOYvkclkV49zeEUDWA4EvLL5VlC4U16BxRTCplpTg&s=10", url: "https://www.retrogames.cc/embed/43080-dragon-ball-origins-2-usa-en-fr-es.html"},
            { title: "Dragon Ball Z: Attack of the Saiyans", image: "https://upload.wikimedia.org/wikipedia/pt/e/ef/DBZ_Attack_of_the_Saiyans_capa.png", url: "https://www.retrogames.cc/embed/39503-dragon-ball-z-attack-of-the-saiyans-europe-en-fr-de-es-it.html"},
            { title: "Power Rangers: Samurai", image: "https://m.media-amazon.com/images/I/81NznaurhOL._AC_UF1000,1000_QL80_.jpg", url: "https://www.retrogames.cc/embed/46620-power-rangers-samurai-usa-en-fr-es.html"},
            { title: "Power Rangers: Super Legends", image: "https://m.media-amazon.com/images/I/61TJQ1nLiuL.jpg", url: "https://www.retrogames.cc/embed/36677-power-rangers-super-legends-usa-en-fr-de-es-it.html"},
            { title: "Metroid Prime: Hunters", image: "https://upload.wikimedia.org/wikipedia/pt/d/da/Metroid_Prime_Hunters_cover.png", url: "https://www.retrogames.cc/embed/35570-metroid-prime-hunters-europe-en-fr-de-es-it.html"},
        ]
    },
    "Clássicos do SNES": { 
        key: "SNES", 
        games: [
            { title: "Mega Man X", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMGXgwmCZXv9V65PlsE5nqXz1eEtH1ItF9rsbydxg9Rw5yMg1gwqr-vY3R&s=10", url: "https://www.retrogames.cc/embed/18705-megaman-x-usa-rev-a.html" },
            { title: "Mega Man X2", image: "https://upload.wikimedia.org/wikipedia/pt/e/e0/Capa_Mega_Man_X2.jpg", url: "https://www.retrogames.cc/embed/19996-megaman-x2-usa.html" },
            { title: "Mega Man X3", image: "https://upload.wikimedia.org/wikipedia/pt/d/d8/Capa_Mega_Man_X3.jpg", url: "https://www.retrogames.cc/embed/22454-megaman-x3-europe.html" },
            { title: "Mega Man 7", image: "https://upload.wikimedia.org/wikipedia/pt/f/f8/Mega_Man_7_capa.jpg", url: "https://www.retrogames.cc/embed/16692-megaman-vii-usa.html" },
            { title: "Mega Man Soccer", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs4dWjqNP31cy3JYJoP4_LXFSJ9tAwUhva0GXKk5-6ABuZFaZNgKf6DLk&s=10", url: "https://www.retrogames.cc/embed/22454-megaman-x3-europe.html" },
            { title: "Mega Man & Bass", image: "https://i.pinimg.com/736x/9a/43/3a/9a433a286f6cc72aff387cd52a6dceb3.jpg", url: "https://www.retrogames.cc/embed/43955-megaman-bass.html" },
            { title: "Marvel Super Heroes: War of the Gems", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdlw45E-QXih05uKjd86nF-g_W-EVwys8HWdnGqzNppVLhyWHIxivfDAU&s=10", url: "https://www.retrogames.cc/embed/22520-marvel-super-heroes-war-of-the-gems-usa.html"},
            { title: "Mickey's Playtown Adventure", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShIOxJlPPW4zoWkLJjWGNOrDv3FGZx2r5oIT8iFYKVV_WB4OwgKZK6vINt&s=10", url: "https://www.retrogames.cc/embed/24180-mickey-s-playtown-adventure-a-day-of-discovery-usa-proto.html"},
            { title: "Mickey to Minnie: Magical Adventure 2", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSohAD1HZ5GRzoeev1wZxm7RhCDsfriwDgGfLN0mytGVWWNTizxJfqJPX5g&s=10", url: "https://www.retrogames.cc/embed/19633-mickey-to-minnie-magical-adventure-2-japan.html"},
            { title: "Mickey to Donald: Magical Adventure 3", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjxOPWcgh2IaejKADMzxUoRSHq0z2Vfuwj35nnik4GqxWCtMsJ4Dyv1gw&s=10", url: "https://www.retrogames.cc/embed/19646-mickey-to-donald-magical-adventure-3-japan-en-by-rpgone-v1-1-mickey-donald-magical-adventure-3.html"},
            { title: "Mighty Morphin Power Rangers - The Movie", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4QLQzyMWGS6fXv5LOEI7mt5OjOQwlXTJaq7k36HigPRnHruwLp-SXjis&s=10", url: "https://www.retrogames.cc/embed/19560-mighty-morphin-power-rangers-the-movie-usa.html"},
            { title: "Mighty Morphin Power Rangers", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgQaS_XDCT9E_dyNXijjDIGlQDVBp6xk9IZ4RSQ7B1s9BaEU4eRIbLTxFq&s=10", url: "https://www.retrogames.cc/embed/24474-mighty-morphin-power-rangers-europe.html"},
            { title: "Mighty Morphin Power Rangers: The Fighting Edition", image: "https://i.ytimg.com/vi/jMPcDUWghHM/maxresdefault.jpg", url: "https://www.retrogames.cc/embed/23323-mighty-morphin-power-rangers-the-fighting-edition-usa.html"},
        ]
    },
};
